name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TB_ADMIN_USERNAME: ${{ secrets.TB_ADMIN_USERNAME }}
      TB_ADMIN_PASSWORD: ${{ secrets.TB_ADMIN_PASSWORD }}
      TB_USER_USERNAME: ${{ secrets.TB_USER_USERNAME }}
      TB_USER_PASSWORD: ${{ secrets.TB_USER_PASSWORD }}
      TB_BASE_URL: ${{ secrets.TB_BASE_URL }}
      TB_USER_USERNAME_2: ${{ secrets.TB_USER_USERNAME_2 }}
      TB_USER_PASSWORD_2: ${{ secrets.TB_USER_PASSWORD_2 }}
      TB_STAFF_USERNAME: ${{ secrets.TB_STAFF_USERNAME}}
      TB_STAFF_PASSWORD: ${{ secrets.TB_STAFF_PASSWORD}}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    # Cache Playwright browsers
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --project=chromium

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
